# Generated by Django 4.2.29 on 2026-03-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('manual', 'Manual Text'), ('txt', 'TXT File Upload'), ('csv', 'CSV File Upload'), ('url', 'URL Scrape')], default='manual', max_length=10)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('num_topics', models.IntegerField(default=5)),
                ('num_words', models.IntegerField(default=10)),
                ('results_json', models.TextField(blank=True, default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
